// Automatically generated by MockGen. DO NOT EDIT!
// Source: ..\src\github.com\ekyoung\personal-site-go\gin-wrapper\wrapper.go

package mock_wrapper

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Context interface
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *_MockContextRecorder
}

// Recorder for MockContext (not exported)
type _MockContextRecorder struct {
	mock *MockContext
}

func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &_MockContextRecorder{mock}
	return mock
}

func (_m *MockContext) EXPECT() *_MockContextRecorder {
	return _m.recorder
}

func (_m *MockContext) Param(key string) string {
	ret := _m.ctrl.Call(_m, "Param", key)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockContextRecorder) Param(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Param", arg0)
}

func (_m *MockContext) HTML(code int, name string, obj interface{}) {
	_m.ctrl.Call(_m, "HTML", code, name, obj)
}

func (_mr *_MockContextRecorder) HTML(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HTML", arg0, arg1, arg2)
}
