// Automatically generated by MockGen. DO NOT EDIT!
// Source: ..\src\github.com\ekyoung\personal-site-go\server\trips\trip-controller.go

package mock_trips

import (
	wrapper "github.com/ekyoung/personal-site-go/gin-wrapper"
	gomock "github.com/golang/mock/gomock"
)

// Mock of PageNotFounder interface
type MockPageNotFounder struct {
	ctrl     *gomock.Controller
	recorder *_MockPageNotFounderRecorder
}

// Recorder for MockPageNotFounder (not exported)
type _MockPageNotFounderRecorder struct {
	mock *MockPageNotFounder
}

func NewMockPageNotFounder(ctrl *gomock.Controller) *MockPageNotFounder {
	mock := &MockPageNotFounder{ctrl: ctrl}
	mock.recorder = &_MockPageNotFounderRecorder{mock}
	return mock
}

func (_m *MockPageNotFounder) EXPECT() *_MockPageNotFounderRecorder {
	return _m.recorder
}

func (_m *MockPageNotFounder) PageNotFound(c wrapper.Context) {
	_m.ctrl.Call(_m, "PageNotFound", c)
}

func (_mr *_MockPageNotFounderRecorder) PageNotFound(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PageNotFound", arg0)
}
